import { ResourceId } from '../../types/game.types';

export interface ResourceDefinition {
  id: ResourceId;
  name: string;
  description: string;
  flavorText?: string; // Fun extra text shown on hover
  category: 'raw' | 'intermediate' | 'food' | 'final';
  tier?: number;
  icon: string;
}

export const RESOURCES: Partial<Record<ResourceId, ResourceDefinition>> = {
  // === LUSH FOREST - RAW ===
  wood: {
    id: 'wood',
    name: 'Wood',
    description: 'The building block of civilization. Also good for chewing when stressed. Not that you\'re stressed. You\'re fine. Everything is fine.',
    flavorText: 'It\'s log! It\'s log! It\'s better than bad, it\'s good!',
    category: 'raw',
    icon: '🪵',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    description: 'It\'s a rock. Rocks are everywhere. You\'d think after advancing to spacefaring civilization we\'d be done with rocks. Nope.',
    flavorText: 'The pioneers used to ride these babies for miles.',
    category: 'raw',
    icon: '🪨',
  },
  berries: {
    id: 'berries',
    name: 'Berries',
    description: 'Colorful, edible, and not poisonous! You checked. Twice. Okay, three times.',
    flavorText: 'Tastes like survival!',
    category: 'food',
    icon: '🫐',
  },
  rubber_sap: {
    id: 'rubber_sap',
    name: 'Rubber Sap',
    description: 'Sticky tree juice that becomes bouncy when processed. Nature is weird but useful.',
    flavorText: 'Do not confuse with maple syrup. Trust me on this one.',
    category: 'raw',
    icon: '🍯',
  },
  nitrogen_nodules: {
    id: 'nitrogen_nodules',
    name: 'Nitrogen Nodules',
    description: 'Little lumps of nitrogen-fixing bacteria. They\'re doing their best. We should all be more like nitrogen nodules.',
    flavorText: 'The unsung heroes of the nitrogen cycle.',
    category: 'raw',
    icon: '🟤',
  },

  // === MISTY LAKE - RAW ===
  fresh_water: {
    id: 'fresh_water',
    name: 'Fresh Water',
    description: 'H₂O. The good stuff. Not the salty kind that makes you more thirsty. Been there, done that, cried a little.',
    flavorText: 'Certified 99.9% not space-poison!',
    category: 'raw',
    icon: '💧',
  },
  fish: {
    id: 'fish',
    name: 'Fish',
    description: 'Aquatic protein sources that don\'t seem to mind being caught. Suspiciously compliant, actually.',
    flavorText: 'They have a 3-second memory. You have a 3-lifetime crash landing streak. Who\'s really winning?',
    category: 'raw',
    icon: '🐟',
  },
  clay: {
    id: 'clay',
    name: 'Clay',
    description: 'Squishy mud that becomes useful mud when you heat it up. Progress!',
    flavorText: 'Makes you feel like a pottery YouTuber. Very zen.',
    category: 'raw',
    icon: '🟫',
  },

  // === ARID DESERT - RAW ===
  quartz_sand: {
    id: 'quartz_sand',
    name: 'Quartz Sand',
    description: 'Sand, but the fancy kind. Gets absolutely everywhere. Your fur will never be the same.',
    flavorText: 'I don\'t like sand. It\'s coarse and rough and irritating.',
    category: 'raw',
    icon: '🏜️',
  },
  crude_oil: {
    id: 'crude_oil',
    name: 'Crude Oil',
    description: 'Ancient organic matter compressed over millions of years. The planet basically made this for you. How thoughtful!',
    flavorText: 'Some call it black gold. You call it "that stuff that stains everything."',
    category: 'raw',
    icon: '🛢️',
  },
  cactus: {
    id: 'cactus',
    name: 'Cactus',
    description: 'A spiky water storage unit that actively doesn\'t want to be touched. Relatable, honestly.',
    flavorText: 'Nature\'s way of saying "personal space is important."',
    category: 'raw',
    icon: '🌵',
  },
  sulfur: {
    id: 'sulfur',
    name: 'Sulfur',
    description: 'Yellow rocks that smell like regret and rotten eggs. Essential for chemistry though, so we tolerate it.',
    flavorText: 'Smells like hell. Useful like heaven. Chemistry is weird.',
    category: 'raw',
    icon: '💛',
  },

  // === FROZEN TUNDRA - RAW ===
  ice: {
    id: 'ice',
    name: 'Ice',
    description: 'Frozen water. Revolutionary stuff. You can make regular water by just... waiting. Patience: the cheapest manufacturing process.',
    flavorText: 'Nature\'s refrigerator. Also nature\'s slip-and-fall hazard.',
    category: 'raw',
    icon: '🧊',
  },
  rutile_ore: {
    id: 'rutile_ore',
    name: 'Rutile Ore',
    description: 'Contains titanium, the metal of the future! Also the metal of spacecraft. Convenient that it\'s here, almost like this game was designed.',
    flavorText: 'Named after the Latin "rutilus" meaning "you\'re gonna need a lot of this."',
    category: 'raw',
    icon: '⛏️',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    description: 'The backbone of industry since forever. If civilization had a favorite element, iron would win by a landslide.',
    flavorText: 'Fe fi fo fum, I smell the blood of industrial revolution.',
    category: 'raw',
    icon: '⛏️',
  },
  arctic_moss: {
    id: 'arctic_moss',
    name: 'Arctic Moss',
    description: 'Surprisingly nutritious moss that survives freezing temperatures. A real overachiever in the plant world.',
    flavorText: 'When life gives you tundra, make tundra salad.',
    category: 'raw',
    icon: '🌿',
  },

  // === VOLCANIC ISLE - RAW ===
  nickel_cobalt_ore: {
    id: 'nickel_cobalt_ore',
    name: 'Nickel-Cobalt Ore',
    description: 'Two metals, one ore! It\'s like a BOGO deal from the planet. Essential for batteries that don\'t explode. Mostly.',
    flavorText: 'The forbidden trail mix.',
    category: 'raw',
    icon: '🔶',
  },
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Volcanic glass. Sharp, shiny, and makes you feel like you\'re in a fantasy game. You\'re not. This is real. Unfortunately.',
    flavorText: 'Looks cool. Cuts literally everything. Handle with extreme caution and mittens.',
    category: 'raw',
    icon: '🖤',
  },
  geothermal_energy: {
    id: 'geothermal_energy',
    name: 'Geothermal Energy',
    description: 'Free energy from the planet\'s angry insides. Like geothermal, but angrier.',
    flavorText: 'The planet is literally giving you free heating. Say thank you.',
    category: 'raw',
    icon: '🔥',
  },

  // === CRYSTAL CAVERNS - RAW ===
  lithium_crystals: {
    id: 'lithium_crystals',
    name: 'Lithium Crystals',
    description: 'Pink glowing crystals containing lithium. Every battery company\'s dream. Also quite pretty. Don\'t eat them.',
    flavorText: 'The forbidden rock candy.',
    category: 'raw',
    icon: '💎',
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Copper Ore',
    description: 'Orange-ish rocks containing copper. Humanity\'s first metal BFF. The relationship is still going strong.',
    flavorText: 'Been carrying civilization since 3300 BCE. No pressure.',
    category: 'raw',
    icon: '🟠',
  },
  phosphorus: {
    id: 'phosphorus',
    name: 'Phosphorus',
    description: 'Glows in the dark and is essential for semiconductors. Nature\'s nightlight AND tech enabler. Multitasking king.',
    flavorText: 'Discovered by someone boiling urine. Science is gross but effective.',
    category: 'raw',
    icon: '✨',
  },
  quartz_crystals: {
    id: 'quartz_crystals',
    name: 'Quartz Crystals',
    description: 'Pure crystalline quartz. Like the sand version but went to finishing school.',
    flavorText: 'The fancy cousin of regular sand. Thinks it\'s better than you. It might be right.',
    category: 'raw',
    icon: '💠',
  },

  // === TIER 1 INTERMEDIATE ===
  planks: {
    id: 'planks',
    name: 'Planks',
    description: 'Flat wood. Somehow this simple transformation is the foundation of all progress. Engineering!',
    flavorText: 'Wood, but flatter. Nobel Prize pending.',
    category: 'intermediate',
    tier: 1,
    icon: '📏',
  },
  stone_bricks: {
    id: 'stone_bricks',
    name: 'Stone Bricks',
    description: 'Stones, but rectangular. The shape that changed architecture forever. Circles are overrated anyway.',
    flavorText: 'Finally, rocks that stack properly.',
    category: 'intermediate',
    tier: 1,
    icon: '🧱',
  },
  charcoal: {
    id: 'charcoal',
    name: 'Charcoal',
    description: 'Burnt wood that burns better than regular wood. Fire science is counterintuitive but we don\'t question it.',
    flavorText: 'Set fire to wood to make better fire fuel. Logic!',
    category: 'intermediate',
    tier: 1,
    icon: '⚫',
  },
  clean_water: {
    id: 'clean_water',
    name: 'Clean Water',
    description: 'Water, but without the weird floaty bits. Your stomach thanks you.',
    flavorText: 'Now with 100% less mystery particles!',
    category: 'intermediate',
    tier: 1,
    icon: '💦',
  },
  rubber: {
    id: 'rubber',
    name: 'Rubber',
    description: 'Bouncy, stretchy, and essential for sealing things. Nature\'s gasket material.',
    flavorText: 'Boing! That\'s the sound of progress.',
    category: 'intermediate',
    tier: 1,
    icon: '⚫',
  },
  ceramics: {
    id: 'ceramics',
    name: 'Ceramics',
    description: 'Baked clay that can handle extreme heat. Ancient technology, still relevant.',
    flavorText: 'Pottery class finally paying off.',
    category: 'intermediate',
    tier: 1,
    icon: '🏺',
  },

  // === TIER 2 INTERMEDIATE ===
  glass: {
    id: 'glass',
    name: 'Glass',
    description: 'Sand that got so hot it became see-through. The original extreme makeover.',
    flavorText: 'Windows, beakers, and dramatic smashing scenes. Versatile!',
    category: 'intermediate',
    tier: 2,
    icon: '🪟',
  },
  iron_ingots: {
    id: 'iron_ingots',
    name: 'Iron Ingots',
    description: 'The strong silent type of metal. Doesn\'t talk much but gets things done.',
    flavorText: 'The heavy metal that\'s actually useful. Sorry, lead.',
    category: 'intermediate',
    tier: 2,
    icon: '⬛',
  },
  aluminum_ingots: {
    id: 'aluminum_ingots',
    name: 'Aluminum Ingots',
    description: 'Lightweight metal that used to be more valuable than gold. Markets are weird.',
    flavorText: 'Once fit for kings, now fit for soda cans. How the mighty have fallen.',
    category: 'intermediate',
    tier: 2,
    icon: '🪙',
  },
  obsidian_tools: {
    id: 'obsidian_tools',
    name: 'Obsidian Tools',
    description: 'Razor-sharp tools made from volcanic glass. Cuts through problems like butter.',
    flavorText: 'When regular tools just won\'t cut it. Literally.',
    category: 'intermediate',
    tier: 2,
    icon: '🔪',
  },
  vulcanized_rubber: {
    id: 'vulcanized_rubber',
    name: 'Vulcanized Rubber',
    description: 'Rubber that\'s been heated with sulfur. Stronger, more durable, and named after a god. Fancy.',
    flavorText: 'Regular rubber\'s cooler cousin who studied abroad.',
    category: 'intermediate',
    tier: 2,
    icon: '🛞',
  },
  copper_wire: {
    id: 'copper_wire',
    name: 'Copper Wire',
    description: 'Thin copper that carries electricity. The nervous system of any factory.',
    flavorText: 'Caution: Do not lick while powered. Actually, don\'t lick any of this stuff.',
    category: 'intermediate',
    tier: 2,
    icon: '🔌',
  },
  hydrogen: {
    id: 'hydrogen',
    name: 'Hydrogen',
    description: 'The lightest element! Also the most explosive when mixed with oxygen. Handle with care and crossed paws.',
    flavorText: 'H. Just H. Simple but will absolutely explode if you look at it wrong.',
    category: 'intermediate',
    tier: 2,
    icon: '💨',
  },
  oxygen: {
    id: 'oxygen',
    name: 'Oxygen',
    description: 'The breathable one! Also essential for explosions. Oxygen does a lot of things.',
    flavorText: 'O. You literally cannot live without it. No pressure.',
    category: 'intermediate',
    tier: 2,
    icon: '🫧',
  },
  kerosene: {
    id: 'kerosene',
    name: 'Kerosene (RP-1)',
    description: 'Refined oil that rockets love. Basically dino juice that goes to space. What a journey.',
    flavorText: 'From dead dinosaurs to the stars. The ultimate glow-up.',
    category: 'intermediate',
    tier: 2,
    icon: '⛽',
  },
  ammonia: {
    id: 'ammonia',
    name: 'Ammonia',
    description: 'Nitrogen and hydrogen had a baby. It smells terrible but is surprisingly useful.',
    flavorText: 'The smell of chemistry class and broken dreams.',
    category: 'intermediate',
    tier: 2,
    icon: '🧪',
  },
  silicon_ingot: {
    id: 'silicon_ingot',
    name: 'Silicon Ingot',
    description: 'The foundation of all computing. Without this, no video games. Let that sink in.',
    flavorText: 'Sand, but with a computer science degree.',
    category: 'intermediate',
    tier: 2,
    icon: '🔲',
  },
  precision_quartz: {
    id: 'precision_quartz',
    name: 'Precision Quartz',
    description: 'Quartz cut so precisely it vibrates at exact frequencies. The heartbeat of electronics.',
    flavorText: 'Oscillating at the frequency of progress.',
    category: 'intermediate',
    tier: 2,
    icon: '💎',
  },
  hull_plates: {
    id: 'hull_plates',
    name: 'Hull Plates',
    description: 'Thick metal plates for spacecraft. Your ticket home, one piece at a time.',
    flavorText: 'Some assembly required. Spaceship not included.',
    category: 'intermediate',
    tier: 2,
    icon: '🛡️',
  },
  tank_shell: {
    id: 'tank_shell',
    name: 'Tank Shell',
    description: 'Empty containers waiting to hold rocket fuel or oxygen. Very patient.',
    flavorText: 'A container with dreams of space travel.',
    category: 'intermediate',
    tier: 2,
    icon: '🛢️',
  },
  aluminum_frame: {
    id: 'aluminum_frame',
    name: 'Aluminum Frame',
    description: 'Lightweight structural supports. The skeleton of your future spacecraft.',
    flavorText: 'Strong bones for a strong ship.',
    category: 'intermediate',
    tier: 2,
    icon: '🔲',
  },
  cathode_powder: {
    id: 'cathode_powder',
    name: 'Cathode Powder',
    description: 'Special powder for battery cathodes. Science dust, basically.',
    flavorText: 'Don\'t sneeze near this stuff.',
    category: 'intermediate',
    tier: 2,
    icon: '🧂',
  },
  refined_alloy: {
    id: 'refined_alloy',
    name: 'Refined Alloy',
    description: 'A premium metal blend for high-performance parts. The good stuff.',
    flavorText: 'Metals that learned to work together.',
    category: 'intermediate',
    tier: 2,
    icon: '🔷',
  },

  // === TIER 3 INTERMEDIATE ===
  liquid_oxygen: {
    id: 'liquid_oxygen',
    name: 'Liquid Oxygen',
    description: 'Oxygen so cold it became a liquid. Essential for rocket fuel and dramatic movie scenes.',
    flavorText: 'LOX: Not the fish kind.',
    category: 'intermediate',
    tier: 3,
    icon: '🧊',
  },
  doped_silicon: {
    id: 'doped_silicon',
    name: 'Doped Silicon',
    description: 'Silicon with carefully added impurities. Sometimes imperfection leads to perfection.',
    flavorText: 'Perfectly impure. An oxymoron, but it works.',
    category: 'intermediate',
    tier: 3,
    icon: '💠',
  },
  graphite: {
    id: 'graphite',
    name: 'Graphite',
    description: 'Carbon arranged just right. Same element as diamonds but took a different career path.',
    flavorText: 'Diamonds are forever. Graphite is more practical.',
    category: 'intermediate',
    tier: 3,
    icon: '✏️',
  },
  hydrazine: {
    id: 'hydrazine',
    name: 'Hydrazine',
    description: 'Rocket fuel component that\'s extremely toxic. Handle with care. And gloves. And distance.',
    flavorText: 'Warning: Not for consumption. Obviously.',
    category: 'intermediate',
    tier: 3,
    icon: '☠️',
  },
  insulation: {
    id: 'insulation',
    name: 'Insulation',
    description: 'Keeps heat in or out. Doesn\'t care which way, just does its job.',
    flavorText: 'The unsung hero of temperature management.',
    category: 'intermediate',
    tier: 3,
    icon: '🧶',
  },

  // === TIER 4 INTERMEDIATE ===
  battery_cells: {
    id: 'battery_cells',
    name: 'Battery Cells',
    description: 'Individual power storage units. Combine for more power. It\'s like Voltron but for electricity.',
    flavorText: 'Stores energy for when you really need it. Like escaping a planet.',
    category: 'intermediate',
    tier: 4,
    icon: '🔋',
  },
  solar_cells: {
    id: 'solar_cells',
    name: 'Solar Cells',
    description: 'Converts sunlight into electricity. Free energy! Except for the manufacturing costs.',
    flavorText: 'The sun is just a giant free battery. Take advantage.',
    category: 'intermediate',
    tier: 4,
    icon: '☀️',
  },

  // === FOOD ===
  cactus_juice: {
    id: 'cactus_juice',
    name: 'Cactus Juice',
    description: 'Refreshing desert nectar squeezed from prickly plants. Hydrating and surprisingly tasty!',
    flavorText: 'It\'ll quench ya! Nothing\'s quenchier!',
    category: 'food',
    icon: '🧃',
  },
  smoked_fish: {
    id: 'smoked_fish',
    name: 'Smoked Fish',
    description: 'Preserved protein that tastes like campfire memories.',
    flavorText: 'That\'s the point of smoking it.',
    category: 'food',
    icon: '🐟',
  },
  // === FINAL PRODUCTS ===
  microchips: {
    id: 'microchips',
    name: 'Microchips',
    description: 'Tiny silicon brains for your spacecraft. They think so you don\'t have to.',
    flavorText: 'Billions of transistors, zero personality.',
    category: 'final',
    icon: '🖥️',
  },
  rocket_fuel: {
    id: 'rocket_fuel',
    name: 'Rocket Fuel',
    description: 'The stuff that makes rockets go woosh. Highly explosive. Handle accordingly.',
    flavorText: 'Controlled explosions: the secret to space travel.',
    category: 'final',
    icon: '🚀',
  },
  thrusters: {
    id: 'thrusters',
    name: 'Thrusters',
    description: 'Engines that push your ship through space. The muscles of your escape plan.',
    flavorText: 'Turns fuel into freedom.',
    category: 'final',
    icon: '🔥',
  },
  oxygen_tanks: {
    id: 'oxygen_tanks',
    name: 'Oxygen Tanks',
    description: 'Portable breathing supply for your space journey. Kind of important.',
    flavorText: 'Breathing is optional... wait, no it\'s not.',
    category: 'final',
    icon: '🫁',
  },
  batteries: {
    id: 'batteries',
    name: 'Batteries',
    description: 'Assembled power storage for your ship. Keeps the lights on in the void.',
    flavorText: 'Not included. Oh wait, you\'re making them. They are included.',
    category: 'final',
    icon: '🔋',
  },
  solar_arrays: {
    id: 'solar_arrays',
    name: 'Solar Arrays',
    description: 'Large solar panel assemblies. Free energy in space, where the sun always shines.',
    flavorText: 'Gathering starlight to power your dreams.',
    category: 'final',
    icon: '🌞',
  },
  titanium_hull: {
    id: 'titanium_hull',
    name: 'Titanium Hull',
    description: 'The outer shell of your spacecraft. Keeps the space out and you in.',
    flavorText: 'Home is where the hull is.',
    category: 'final',
    icon: '🛸',
  },
};

// Helper function to check if a resource is defined
export function getResourceDef(id: ResourceId): ResourceDefinition | undefined {
  return RESOURCES[id];
}

export function getResourceName(id: ResourceId): string {
  return RESOURCES[id]?.name || id;
}
